const infiniteWord = [
  "Communication",
  "Écoute",
  "Clarté",
  "Collaboration",
  "Travail d'équipe",
  "Flexibilité",
  "Adaptabilité",
  "Organisation",
  "Gestion du temps",
  "Autonomie",
  "Proactivité",
  "Résolution de problèmes",
  "Pensée analytique",
  "Créativité",
  "Apprentissage continu",
  "Curiosité",
  "Empathie",
  "Satisfaction client",
  "Gestion du stress",
  "Intégrité",
  "Fiabilité",
  "Leadership",
  "Motivation",
  "Initiative",
  "Patience",
  "Persévérance",
  "Sens des responsabilités",
  "Esprit critique",
  "Esprit d'initiative",
  "Adaptation rapide",
  "Esprit d'équipe",
  "Réactivité",
  "Sens de l'organisation",
  "Sens de l'écoute",
  "Collaboration interfonctionnelle",
  "Communication efficace",
  "Travail sous pression",
  "Priorisation",
  "Gestion des priorités",
  "Détermination",
  "Souplesse",
  "Adaptation au changement",
  "Créativité",
  "Sensibilité aux besoins clients",
  "Esprit de synthèse",
  "Sens du détail",
  "Gestion des émotions",
  "Leadership",
  "Gestion des conflits",
  "Esprit de service",
  "Orientation résultats",
  "Esprit d'équipe",
  "Esprit critique",
  "Esprit d'initiative",
  "Adaptation rapide",
  "Esprit d'équipe",
  "Réactivité",
  "Sens de l'organisation",
  "Sens de l'écoute",
  "Collaboration interfonctionnelle",
  "Travail sous pression",
  "Priorisation",
  "Gestion des priorités",
  "Détermination",
  "Souplesse",
  "Adaptation au changement",
  "Créativité",
  "Sensibilité aux besoins clients",
  "Esprit de synthèse",
  "Sens du détail",
  "Gestion des émotions",
  "Leadership",
  "Gestion des conflits",
  "Esprit de service",
  "Orientation résultats",
  "Esprit d'équipe",
  "Prise de décision",
  "Persuasion",
  "Éthique professionnelle",
  "Innovation",
  "Résilience",
  "Empathie",
  "Équilibre travail-vie personnelle",
  "Mentorat",
  "Capacité d'écoute",
  "Adaptabilité culturelle",
  "Capacité à travailler en réseau",
  "Esprit collaboratif",
  "Gestion du temps",
  "Gestion du stress",
  "Responsabilité",
  "Confiance en soi",
];

export default infiniteWord;
